version: '1.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeigniter-app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - ci_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: codeigniter-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ci4db
      MYSQL_USER: ci4user
      MYSQL_PASSWORD: ci4password
    ports:
      - "3306:3306"
    networks:
      - ci_network

networks:
  ci_network:
    driver: bridge
