<?php namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use ReflectionException;

/**
 * Short description of this class usages
 * @class EmployeesSeeder
 * @generated_by RobinNcode\db_craft
 * @package App\Database\Seeds
 * @extend CodeIgniter\Database\Seeder
 * @generated_at 03 September, 2024 10:20:49 PM
 */

class EmployeesSeeder extends Seeder
{
    /**
     * @throws ReflectionException
     */
    public function run(): void
    {
        // Table Data ...
        $employees = [
            ['id' => '1','branch_id' => '2','designation_id' => '1','name' => 'Abdur rahim','code' => '001','fathers_name' => 'Abdur rahman','mothers_name' => 'Rehana begum','spouse_name' => 'Fatema','permanent_address' => 'Vill+Post: Aminabad, Thana: Charfassion, Dist: Bhola','present_address' => 'Vill+Post: Aminabad, Thana: Charfassion, Dist: Bhola','last_achieved_degree' => '1','date_of_birth' => '1993-03-05','date_of_joining' => '2016-01-02','date_of_discontinue' => NULL,'secuirity_money' => '0.00','starting_salary' => '0.00','current_salary' => '25000.00','national_id' => '0','smart_id' => '2351129180','blood_group' => 'AB+','gender' => 'M','mobile_no' => '01733158070','email' => 'reponaminabad@gmail.com','status' => '1','employee_picture' => NULL,'refence_info_1' => '','refence_info_2' => '','attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '1','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '2','branch_id' => '2','designation_id' => '2','name' => 'Shaidul islam','code' => '002','fathers_name' => 'Soyed mazi','mothers_name' => 'Bibi Khadiza','spouse_name' => 'null','permanent_address' => 'Vill: halimabad, Post: Aminabad, Thana: Charfassion, Dist: Bhola','present_address' => 'Vill: halimabad, Post: Aminabad, Thana: Charfassion, Dist: Bhola','last_achieved_degree' => '1','date_of_birth' => '2002-01-01','date_of_joining' => '2020-03-14','date_of_discontinue' => NULL,'secuirity_money' => '0.00','starting_salary' => '4000.00','current_salary' => '8000.00','national_id' => '0','smart_id' => '0','blood_group' => 'A+','gender' => 'M','mobile_no' => '01739497354','email' => 'null','status' => '0','employee_picture' => NULL,'refence_info_1' => 'null','refence_info_2' => 'null','attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '3','branch_id' => '2','designation_id' => '4','name' => 'Md. Ismile','code' => '003','fathers_name' => 'Md. Giyas uddin','mothers_name' => 'Firoja begum','spouse_name' => 'Mst. Jannat','permanent_address' => 'Vill: Abubakarpur, Post: Aminabad, Thana: Charfassion, Dist: Bhola','present_address' => 'Vill: Abubakarpur, Post: Aminabad, Thana: Charfassion, Dist: Bhola','last_achieved_degree' => '1','date_of_birth' => '1998-12-10','date_of_joining' => '2022-03-01','date_of_discontinue' => NULL,'secuirity_money' => NULL,'starting_salary' => '8000.00','current_salary' => '8000.00','national_id' => NULL,'smart_id' => '0','blood_group' => '0','gender' => 'M','mobile_no' => '01762447073','email' => 'null','status' => '1','employee_picture' => NULL,'refence_info_1' => 'null','refence_info_2' => 'null','attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '4','branch_id' => '2','designation_id' => '3','name' => 'Mahedi hasan','code' => '004','fathers_name' => 'Md. Bellal','mothers_name' => 'Anowra begum','spouse_name' => NULL,'permanent_address' => 'Vill: Halimabad, Post: Aminabad, Thana: Charfassion, Dist: Bhola','present_address' => 'Vill: Halimabad, Post: Aminabad, Thana: Charfassion, Dist: Bhola','last_achieved_degree' => '1','date_of_birth' => '2001-02-15','date_of_joining' => '2021-09-01','date_of_discontinue' => '2022-12-15','secuirity_money' => NULL,'starting_salary' => '8000.00','current_salary' => '8000.00','national_id' => '0','smart_id' => NULL,'blood_group' => 'B+','gender' => 'M','mobile_no' => '01790052616','email' => NULL,'status' => '0','employee_picture' => NULL,'refence_info_1' => NULL,'refence_info_2' => NULL,'attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '5','branch_id' => '2','designation_id' => '3','name' => 'Md. Helal uddin','code' => '005','fathers_name' => 'Kazol','mothers_name' => 'Aysha khatun','spouse_name' => 'Munni','permanent_address' => 'Vill: Abdullahpur, Post: Dhakhin Shiba, Thana: Charfassion, Dist: Bhola','present_address' => 'Vill: Abdullahpur, Post: Dhakhin Shiba, Thana: Charfassion, Dist: Bhola','last_achieved_degree' => '1','date_of_birth' => '1998-11-01','date_of_joining' => '2021-09-01','date_of_discontinue' => NULL,'secuirity_money' => '0.00','starting_salary' => '8000.00','current_salary' => '9000.00','national_id' => '0','smart_id' => '0','blood_group' => 'AB+','gender' => 'M','mobile_no' => '01714736732','email' => 'null','status' => '1','employee_picture' => NULL,'refence_info_1' => 'null','refence_info_2' => 'null','attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '6','branch_id' => '2','designation_id' => '3','name' => 'Abul kasam badan','code' => '006','fathers_name' => 'Ali akbar','mothers_name' => 'Kamrun nahar','spouse_name' => 'Soniya','permanent_address' => 'Vill+Post: Aminabad, Thana: Charfassion, Dist: Bhola','present_address' => 'Vill+Post: Aminabad, Thana: Charfassion, Dist: Bhola','last_achieved_degree' => '1','date_of_birth' => '1993-12-31','date_of_joining' => '2021-04-01','date_of_discontinue' => '2022-12-22','secuirity_money' => NULL,'starting_salary' => '8000.00','current_salary' => '9000.00','national_id' => '0','smart_id' => NULL,'blood_group' => 'O+','gender' => 'M','mobile_no' => '01884317505','email' => NULL,'status' => '0','employee_picture' => NULL,'refence_info_1' => NULL,'refence_info_2' => NULL,'attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '7','branch_id' => '2','designation_id' => '3','name' => 'Md. Rasel','code' => '007','fathers_name' => 'Md. Abu taher','mothers_name' => 'Rabeya begum','spouse_name' => 'null','permanent_address' => 'Abdullahpur, Ward no: 06, Charfassion, Bhola','present_address' => 'Abdullahpur, Ward no: 06, Charfassion, Bhola','last_achieved_degree' => '1','date_of_birth' => '1997-06-23','date_of_joining' => '2022-04-21','date_of_discontinue' => '2022-12-28','secuirity_money' => '0.00','starting_salary' => '8000.00','current_salary' => '0.00','national_id' => '0','smart_id' => '4653139974','blood_group' => '0','gender' => 'M','mobile_no' => '01712170404','email' => 'null','status' => '0','employee_picture' => NULL,'refence_info_1' => 'Md. Sohel Sikder','refence_info_2' => 'Md. Belal Dr','attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '8','branch_id' => '2','designation_id' => '3','name' => 'Mehedi hassan ','code' => '008','fathers_name' => 'Md. Yousuf','mothers_name' => 'Parvin begum','spouse_name' => 'null','permanent_address' => 'Abubkarpur, Ward: 06, Charfassion, Bhola','present_address' => 'Abubkarpur, Ward: 06, Charfassion, Bhola','last_achieved_degree' => '1','date_of_birth' => '2002-01-02','date_of_joining' => '2022-06-05','date_of_discontinue' => NULL,'secuirity_money' => '0.00','starting_salary' => '8000.00','current_salary' => '0.00','national_id' => NULL,'smart_id' => '4208704546','blood_group' => '0','gender' => 'M','mobile_no' => '01727324597','email' => 'null','status' => '1','employee_picture' => NULL,'refence_info_1' => 'null','refence_info_2' => 'null','attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '9','branch_id' => '2','designation_id' => '3','name' => 'Md. Baker','code' => '009','fathers_name' => 'Jinnat ali mazi','mothers_name' => 'Mazeda begum','spouse_name' => NULL,'permanent_address' => 'Vill: Abdullahpur, Ward: 06, P/S: Charfassion, Dist: Bhola','present_address' => 'Vill: Abdullahpur, Ward: 06, P/S: Charfassion, Dist: Bhola','last_achieved_degree' => '1','date_of_birth' => '1995-01-07','date_of_joining' => '2022-05-10','date_of_discontinue' => '2022-12-15','secuirity_money' => NULL,'starting_salary' => '8000.00','current_salary' => NULL,'national_id' => '0','smart_id' => NULL,'blood_group' => '0','gender' => 'M','mobile_no' => '01852820064','email' => NULL,'status' => '0','employee_picture' => NULL,'refence_info_1' => NULL,'refence_info_2' => NULL,'attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '10','branch_id' => '1','designation_id' => '1','name' => 'Mr. Md Abdur rahim','code' => '010','fathers_name' => 'Abdur rahman','mothers_name' => 'Rehana begum','spouse_name' => 'Fatema','permanent_address' => 'Vill+Post: Aminabad, Thana: Charfassion, Dist: Bhola','present_address' => 'Vill+Post: Aminabad, Thana: Charfassion, Dist: Bhola','last_achieved_degree' => '1','date_of_birth' => '1993-03-05','date_of_joining' => '2016-01-02','date_of_discontinue' => NULL,'secuirity_money' => '0.00','starting_salary' => '0.00','current_salary' => '25000.00','national_id' => '0','smart_id' => '0','blood_group' => 'AB+','gender' => 'M','mobile_no' => '01733158070','email' => 'reponaminabad@gmail.com','status' => '1','employee_picture' => NULL,'refence_info_1' => 'null','refence_info_2' => 'null','attached_documents' => NULL,'is_field_officer' => '0','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '11','branch_id' => '2','designation_id' => '3','name' => 'Md. Riaz','code' => '011','fathers_name' => 'Sahabuddin','mothers_name' => 'Mollika begum','spouse_name' => NULL,'permanent_address' => 'ViLL: Pangasiya Khalgora, Post: Gojariya, Upozila: Lalmohon, Zila: Bhola.','present_address' => 'ViLL: Pangasiya Khalgora, Post: Gojariya, Upozila: Lalmohon, Zila: Bhola.','last_achieved_degree' => '1','date_of_birth' => '1998-01-01','date_of_joining' => '2022-08-01','date_of_discontinue' => '2023-05-29','secuirity_money' => NULL,'starting_salary' => '8000.00','current_salary' => NULL,'national_id' => '0','smart_id' => NULL,'blood_group' => '0','gender' => 'M','mobile_no' => '01764022008','email' => NULL,'status' => '0','employee_picture' => NULL,'refence_info_1' => NULL,'refence_info_2' => NULL,'attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '12','branch_id' => '2','designation_id' => '3','name' => 'Md. Anwar hossen','code' => '012','fathers_name' => 'Nasir Ahammed','mothers_name' => 'Bibi Moriom','spouse_name' => NULL,'permanent_address' => 'Vill: Aowagpur, Ward no: 04, Upozila:Charfassion, Dist: Bhola','present_address' => 'Vill: Aowagpur, Ward no: 04, Upozila:Charfassion, Dist: Bhola','last_achieved_degree' => '1','date_of_birth' => '1998-03-07','date_of_joining' => '2022-10-15','date_of_discontinue' => '2023-05-29','secuirity_money' => NULL,'starting_salary' => '8000.00','current_salary' => NULL,'national_id' => '0','smart_id' => NULL,'blood_group' => 'B+','gender' => 'M','mobile_no' => '01727118356','email' => NULL,'status' => '0','employee_picture' => NULL,'refence_info_1' => NULL,'refence_info_2' => NULL,'attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '13','branch_id' => '2','designation_id' => '3','name' => 'Md. Abu jahar','code' => '013','fathers_name' => 'Munsur Ahammed','mothers_name' => 'Mst. Mahar nigar','spouse_name' => 'Rabeya begum','permanent_address' => 'Vill: Aoyazpur, Ward no: 06, Upozila: Charfassion, Dist: Bhola','present_address' => 'Vill: Aoyazpur, Ward no: 06, Upozila: Charfassion, Dist: Bhola','last_achieved_degree' => '1','date_of_birth' => '1984-01-15','date_of_joining' => '2022-10-15','date_of_discontinue' => '2023-11-02','secuirity_money' => NULL,'starting_salary' => '8000.00','current_salary' => NULL,'national_id' => '0','smart_id' => NULL,'blood_group' => '0','gender' => 'M','mobile_no' => '01894422061','email' => NULL,'status' => '0','employee_picture' => NULL,'refence_info_1' => NULL,'refence_info_2' => NULL,'attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '15','branch_id' => '2','designation_id' => '10','name' => 'Md. Shahin','code' => '015','fathers_name' => 'Md. Moslem mazi','mothers_name' => 'Arju Begum','spouse_name' => NULL,'permanent_address' => 'Vill+Union: Abdullahpur, Ward no: 06, Upozila: Charfassion, Dist: Bhola.','present_address' => 'Vill+Union: Abdullahpur, Ward no: 06, Upozila: Charfassion, Dist: Bhola.','last_achieved_degree' => '1','date_of_birth' => '2003-06-10','date_of_joining' => '2022-12-11','date_of_discontinue' => NULL,'secuirity_money' => NULL,'starting_salary' => '7000.00','current_salary' => NULL,'national_id' => '0','smart_id' => '1515474292','blood_group' => '0','gender' => 'M','mobile_no' => '01729544866','email' => NULL,'status' => '1','employee_picture' => NULL,'refence_info_1' => NULL,'refence_info_2' => NULL,'attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '16','branch_id' => '2','designation_id' => '9','name' => 'Md. Aminul islam','code' => '016','fathers_name' => 'Abdul Jalil','mothers_name' => 'Mst. Rokeya begum','spouse_name' => NULL,'permanent_address' => 'Vill+Union: Osmangong, Upozila: Charfassion, Dist: bhola','present_address' => 'Vill+Union: Osmangong, Upozila: Charfassion, Dist: bhola','last_achieved_degree' => '3','date_of_birth' => '1982-03-01','date_of_joining' => '2023-01-01','date_of_discontinue' => '2023-11-02','secuirity_money' => NULL,'starting_salary' => '9000.00','current_salary' => NULL,'national_id' => '0','smart_id' => '7313716255','blood_group' => '0','gender' => 'M','mobile_no' => '01712561145','email' => NULL,'status' => '0','employee_picture' => NULL,'refence_info_1' => NULL,'refence_info_2' => NULL,'attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '17','branch_id' => '2','designation_id' => '3','name' => 'Md. Mahabub alam','code' => '017','fathers_name' => 'Mostafa','mothers_name' => 'Rahima begum','spouse_name' => NULL,'permanent_address' => 'Vill: Char Afzal, Union: char madraj, Upozila: Charfassion, Dist: bhola.','present_address' => 'Vill: Char Afzal, Union: char madraj, Upozila: Charfassion, Dist: bhola.','last_achieved_degree' => '1','date_of_birth' => '1999-05-01','date_of_joining' => '2023-02-16','date_of_discontinue' => '2023-11-02','secuirity_money' => NULL,'starting_salary' => '8000.00','current_salary' => NULL,'national_id' => '0','smart_id' => '6456085098','blood_group' => '0','gender' => 'M','mobile_no' => '01705545116','email' => NULL,'status' => '0','employee_picture' => NULL,'refence_info_1' => 'Md. Jasim Munshi','refence_info_2' => 'Md. Ismail','attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '18','branch_id' => '2','designation_id' => '9','name' => 'Hasan Mahmud Babu','code' => '018','fathers_name' => 'Abe Abdullah','mothers_name' => 'Tahmina begum','spouse_name' => 'null','permanent_address' => 'Abdullahpur Ward no:02, Charfassion, Bhola','present_address' => 'Abdullahpur Ward no:02, Charfassion, Bhola','last_achieved_degree' => '3','date_of_birth' => '1994-02-07','date_of_joining' => '2023-05-01','date_of_discontinue' => '2024-06-13','secuirity_money' => '0.00','starting_salary' => '9000.00','current_salary' => '0.00','national_id' => NULL,'smart_id' => NULL,'blood_group' => '0','gender' => 'M','mobile_no' => '01765047920','email' => 'null','status' => '0','employee_picture' => NULL,'refence_info_1' => 'Md. Saifur rahman Sabbir 01715793376','refence_info_2' => 'null','attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '19','branch_id' => '2','designation_id' => '10','name' => 'Ahmad Ullah','code' => '019','fathers_name' => 'Md. Nure Alam','mothers_name' => 'Momotaz Begum','spouse_name' => 'Mst. Sabina','permanent_address' => 'Vill: Eoyazpur, Ward no-02, Charfassion, Bhola.','present_address' => 'Vill: Eoyazpur, Ward no-02, Charfassion, Bhola.','last_achieved_degree' => '1','date_of_birth' => '2001-01-01','date_of_joining' => '2023-08-21','date_of_discontinue' => NULL,'secuirity_money' => NULL,'starting_salary' => '7000.00','current_salary' => NULL,'national_id' => NULL,'smart_id' => '3758306637','blood_group' => 'B+','gender' => 'M','mobile_no' => '01756213496','email' => NULL,'status' => '1','employee_picture' => NULL,'refence_info_1' => 'Md. Samim, Osmangong, Charfassion, bhola.','refence_info_2' => NULL,'attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '20','branch_id' => '2','designation_id' => '7','name' => 'Md. Sumon','code' => '020','fathers_name' => 'Md. Sah Jhan','mothers_name' => 'Rizia Begum','spouse_name' => 'Sabina Yasmin Rupa','permanent_address' => 'Pourasaba Ward no: 03, Charfassion, Bhola.','present_address' => 'Pourasaba Ward no: 03, Charfassion, Bhola.','last_achieved_degree' => '3','date_of_birth' => '1986-10-15','date_of_joining' => '2023-08-01','date_of_discontinue' => NULL,'secuirity_money' => NULL,'starting_salary' => '12000.00','current_salary' => NULL,'national_id' => NULL,'smart_id' => NULL,'blood_group' => 'B+','gender' => 'M','mobile_no' => '01710011689','email' => NULL,'status' => '1','employee_picture' => NULL,'refence_info_1' => NULL,'refence_info_2' => NULL,'attached_documents' => NULL,'is_field_officer' => '0','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '21','branch_id' => '2','designation_id' => '3','name' => 'Abul Kashem ','code' => '021','fathers_name' => 'Md. Lokman','mothers_name' => 'Suraia Begum','spouse_name' => NULL,'permanent_address' => 'Osmangong, Ward no-03, Charfassion, Bhola.','present_address' => 'Osmangong, Ward no-03, Charfassion, Bhola.','last_achieved_degree' => '1','date_of_birth' => '2000-10-06','date_of_joining' => '2023-12-01','date_of_discontinue' => NULL,'secuirity_money' => NULL,'starting_salary' => '8000.00','current_salary' => NULL,'national_id' => NULL,'smart_id' => NULL,'blood_group' => '0','gender' => 'M','mobile_no' => '01756377107','email' => NULL,'status' => '1','employee_picture' => NULL,'refence_info_1' => 'Md. Sumon','refence_info_2' => NULL,'attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '22','branch_id' => '2','designation_id' => '10','name' => 'Md. Arif','code' => '022','fathers_name' => 'Md. Ali','mothers_name' => 'Mahmuda ','spouse_name' => 'Liza','permanent_address' => 'Vill+Post: Shoshibussion, Upozila: Charfassion, Dist: Bhola.','present_address' => 'Vill+Post: Shoshibussion, Upozila: Charfassion, Dist: Bhola.','last_achieved_degree' => '3','date_of_birth' => '1998-01-01','date_of_joining' => '2024-01-21','date_of_discontinue' => NULL,'secuirity_money' => NULL,'starting_salary' => '7000.00','current_salary' => NULL,'national_id' => NULL,'smart_id' => NULL,'blood_group' => 'B+','gender' => 'M','mobile_no' => '01795321125','email' => NULL,'status' => '1','employee_picture' => NULL,'refence_info_1' => 'Md. Helal Uddin','refence_info_2' => NULL,'attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '23','branch_id' => '2','designation_id' => '11','name' => 'Md. Raihan','code' => '023','fathers_name' => 'Md. Babul','mothers_name' => 'Bibi Khadiza','spouse_name' => NULL,'permanent_address' => 'Vill: Abdullahpur, Ward no:05, Upozila: Charfassion, Dist: Bhola.','present_address' => 'Vill: Abdullahpur, Ward no:05, Upozila: Charfassion, Dist: Bhola.','last_achieved_degree' => '1','date_of_birth' => '2005-01-02','date_of_joining' => '2023-10-01','date_of_discontinue' => NULL,'secuirity_money' => NULL,'starting_salary' => '6000.00','current_salary' => NULL,'national_id' => NULL,'smart_id' => NULL,'blood_group' => 'O+','gender' => 'M','mobile_no' => '01770015725','email' => NULL,'status' => '1','employee_picture' => NULL,'refence_info_1' => 'Md. Arif Sazi','refence_info_2' => 'Md. Sohel Sikdar','attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
            ['id' => '24','branch_id' => '2','designation_id' => '3','name' => 'Nezam Uddin','code' => '024','fathers_name' => 'Md. Ruhul Amin','mothers_name' => 'Mollika Begum','spouse_name' => 'null','permanent_address' => 'Shashivusion, 1 no Ward, Shashivusion, Charfassion, Bhola.','present_address' => 'Shashivusion, 1 no Ward, Shashivusion, Charfassion, Bhola.','last_achieved_degree' => '1','date_of_birth' => '1978-12-31','date_of_joining' => '2024-06-03','date_of_discontinue' => NULL,'secuirity_money' => '0.00','starting_salary' => '8000.00','current_salary' => '0.00','national_id' => '19780911814104013','smart_id' => '0','blood_group' => '0','gender' => 'M','mobile_no' => '01770357708','email' => 'null','status' => '1','employee_picture' => NULL,'refence_info_1' => 'Hasan Mahmud Babu','refence_info_2' => 'Md. Soyib hawder','attached_documents' => NULL,'is_field_officer' => '1','is_manager' => '0','id_sequence_no' => NULL,'sync_date' => NULL,'field_officer_pin' => NULL,'nominee_info' => NULL,],
        ];


        // Cleaning up the table before seeding ...
        $this->db->table('employees')->truncate();

        //Using Query Builder Class ...
        try {
        $this->db->table('employees')->insertBatch($employees);
        } catch (ReflectionException $e) {
            throw new ReflectionException($e->getMessage());
        }
    }
}
