<?php namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use ReflectionException;

/**
 * Short description of this class usages
 * @class LoanProductsSeeder
 * @generated_by RobinNcode\db_craft
 * @package App\Database\Seeds
 * @extend CodeIgniter\Database\Seeder
 * @generated_at 03 September, 2024 10:20:49 PM
 */

class LoanProductsSeeder extends Seeder
{
    /**
     * @throws ReflectionException
     */
    public function run(): void
    {
        // Table Data ...
        $loan_products = [
            ['id' => '1','name' => 'JAGORON','short_name' => 'JAGO','code' => '01','loan_product_category_id' => '1','is_primary_product' => '1','start_date' => '2016-01-01','minimum_loan_amount' => '5000.00','maximum_loan_amount' => '200000.00','default_loan_amount' => '102500.00','funding_organization_id' => '2','gl_code_for_principal' => NULL,'gl_code_for_interest' => NULL,'grace_period' => '1_W','is_insurance_applicable' => '1','is_multiple_loan_allowed_for_primary_products' => '0','insurance_calculation_method' => '2','maximum_insurance_amount' => NULL,'insurance_amount' => '1','insurance_amount_1' => NULL,'gl_code_for_insurance' => NULL,'gl_code_for_saving_collection' => NULL,'gl_code_for_saving_interest' => NULL,'gl_code_for_skt_collection' => NULL,'number_of_installment' => '45','loan_product_type' => 'R','repayment_frequency' => 'W','eligible_repayment_frequency' => 'W','interest_payment_frequency' => '','mode_of_monthly_collection' => '','monthly_collection_day_or_week' => '','write_off_eligible_years' => '0','loan_form_fee' => '20.00','health_expenditure' => '0.00','risk_insurance' => '0.00000','additional_fee' => '0.00','member_admission_fee' => '0.00','maximum_loan_amount_for_additional_fee_applicable' => '0.00','maximum_loan_amount_for_insurance_applicable' => NULL,'skip_last_week_calculation_monthly' => '0','additional_fee_calculation_method' => '1','mandatory_savings_amount' => '0','is_sms_service_applicable' => '1','minimum_loan_amount_for_sms' => '0','is_actual_daily_basis' => '0','savings_deposit_percentage_new_disburse' => NULL,'savings_deposit_percentage_repeat_disburse' => NULL,'savings_deposit_loan_amount_range' => NULL,'loan_amount_percentage_for_savings_deposit' => NULL,'is_epi' => '0','loan_type' => '','is_fixed_interest_roundup' => '0','audit_fee' => '0','optional_loan_taken' => '0','days_after_disburse' => '0','is_short_term' => '0','is_auto_cal_paramedic_welfare_insurance_amount' => '0','loan_disbursement_stop' => '0','loan_disbursement_stop_from' => '0','loan_disbursement_stop_to' => '0','is_islamic_product' => '0','is_capture_pksf_id' => '0','is_show_auto_process' => '1','insert_time' => '2022-04-07 15:46:32','update_time' => '2023-10-10 14:21:24',],
            ['id' => '2','name' => 'AGROSOR','short_name' => 'AGRO','code' => '02','loan_product_category_id' => '2','is_primary_product' => '1','start_date' => '2010-01-01','minimum_loan_amount' => '10000.00','maximum_loan_amount' => '500000.00','default_loan_amount' => '500000.00','funding_organization_id' => '2','gl_code_for_principal' => NULL,'gl_code_for_interest' => NULL,'grace_period' => '1_M','is_insurance_applicable' => '1','is_multiple_loan_allowed_for_primary_products' => '0','insurance_calculation_method' => '2','maximum_insurance_amount' => NULL,'insurance_amount' => '1','insurance_amount_1' => NULL,'gl_code_for_insurance' => NULL,'gl_code_for_saving_collection' => NULL,'gl_code_for_saving_interest' => NULL,'gl_code_for_skt_collection' => NULL,'number_of_installment' => '12','loan_product_type' => 'R','repayment_frequency' => 'M','eligible_repayment_frequency' => 'M','interest_payment_frequency' => '','mode_of_monthly_collection' => 'DD','monthly_collection_day_or_week' => 'DD','write_off_eligible_years' => '0','loan_form_fee' => '20.00','health_expenditure' => '0.00','risk_insurance' => '0.00000','additional_fee' => '0.00','member_admission_fee' => '0.00','maximum_loan_amount_for_additional_fee_applicable' => '0.00','maximum_loan_amount_for_insurance_applicable' => NULL,'skip_last_week_calculation_monthly' => '0','additional_fee_calculation_method' => '1','mandatory_savings_amount' => '0','is_sms_service_applicable' => '1','minimum_loan_amount_for_sms' => '0','is_actual_daily_basis' => '0','savings_deposit_percentage_new_disburse' => NULL,'savings_deposit_percentage_repeat_disburse' => NULL,'savings_deposit_loan_amount_range' => NULL,'loan_amount_percentage_for_savings_deposit' => NULL,'is_epi' => '0','loan_type' => '','is_fixed_interest_roundup' => '0','audit_fee' => '0','optional_loan_taken' => '0','days_after_disburse' => '0','is_short_term' => '0','is_auto_cal_paramedic_welfare_insurance_amount' => '0','loan_disbursement_stop' => '0','loan_disbursement_stop_from' => '0','loan_disbursement_stop_to' => '0','is_islamic_product' => '0','is_capture_pksf_id' => '0','is_show_auto_process' => '1','insert_time' => '2022-04-07 16:07:48','update_time' => '2023-11-07 14:24:05',],
            ['id' => '3','name' => 'UTTARAN','short_name' => 'UTTARAN','code' => '03','loan_product_category_id' => '3','is_primary_product' => '1','start_date' => '2016-01-03','minimum_loan_amount' => '50000.00','maximum_loan_amount' => '1000000.00','default_loan_amount' => '525000.00','funding_organization_id' => '2','gl_code_for_principal' => NULL,'gl_code_for_interest' => NULL,'grace_period' => '1_M','is_insurance_applicable' => '1','is_multiple_loan_allowed_for_primary_products' => '0','insurance_calculation_method' => '2','maximum_insurance_amount' => NULL,'insurance_amount' => '1.5','insurance_amount_1' => NULL,'gl_code_for_insurance' => NULL,'gl_code_for_saving_collection' => NULL,'gl_code_for_saving_interest' => NULL,'gl_code_for_skt_collection' => NULL,'number_of_installment' => '12,18,24,30,36,45','loan_product_type' => 'R','repayment_frequency' => 'M','eligible_repayment_frequency' => 'M','interest_payment_frequency' => '','mode_of_monthly_collection' => 'DD','monthly_collection_day_or_week' => 'DD','write_off_eligible_years' => '0','loan_form_fee' => '20.00','health_expenditure' => '0.00','risk_insurance' => '0.00000','additional_fee' => '0.00','member_admission_fee' => '0.00','maximum_loan_amount_for_additional_fee_applicable' => '0.00','maximum_loan_amount_for_insurance_applicable' => NULL,'skip_last_week_calculation_monthly' => '0','additional_fee_calculation_method' => '1','mandatory_savings_amount' => '0','is_sms_service_applicable' => '1','minimum_loan_amount_for_sms' => '0','is_actual_daily_basis' => '0','savings_deposit_percentage_new_disburse' => NULL,'savings_deposit_percentage_repeat_disburse' => NULL,'savings_deposit_loan_amount_range' => NULL,'loan_amount_percentage_for_savings_deposit' => NULL,'is_epi' => '0','loan_type' => '','is_fixed_interest_roundup' => '0','audit_fee' => '0','optional_loan_taken' => '0','days_after_disburse' => '0','is_short_term' => '0','is_auto_cal_paramedic_welfare_insurance_amount' => '0','loan_disbursement_stop' => '0','loan_disbursement_stop_from' => '0','loan_disbursement_stop_to' => '0','is_islamic_product' => '0','is_capture_pksf_id' => '0','is_show_auto_process' => '1','insert_time' => '2022-04-10 11:32:51','update_time' => '2024-04-22 11:14:02',],
            ['id' => '4','name' => 'AGROSOR (Cash Credit)','short_name' => 'AGROSOR (CC)','code' => '04','loan_product_category_id' => '2','is_primary_product' => '1','start_date' => '2023-01-01','minimum_loan_amount' => '1000.00','maximum_loan_amount' => '1000000.00','default_loan_amount' => '500500.00','funding_organization_id' => '2','gl_code_for_principal' => NULL,'gl_code_for_interest' => NULL,'grace_period' => '6_M','is_insurance_applicable' => '1','is_multiple_loan_allowed_for_primary_products' => '0','insurance_calculation_method' => '2','maximum_insurance_amount' => NULL,'insurance_amount' => '1','insurance_amount_1' => NULL,'gl_code_for_insurance' => NULL,'gl_code_for_saving_collection' => NULL,'gl_code_for_saving_interest' => NULL,'gl_code_for_skt_collection' => NULL,'number_of_installment' => '1,12','loan_product_type' => 'O','repayment_frequency' => '','eligible_repayment_frequency' => '1,3,4,5,6,7,8,9,12,24,36,48,60,72,84','interest_payment_frequency' => 'O','mode_of_monthly_collection' => '','monthly_collection_day_or_week' => '','write_off_eligible_years' => '3','loan_form_fee' => '20.00','health_expenditure' => '0.00','risk_insurance' => '0.00000','additional_fee' => '0.00','member_admission_fee' => '0.00','maximum_loan_amount_for_additional_fee_applicable' => '0.00','maximum_loan_amount_for_insurance_applicable' => NULL,'skip_last_week_calculation_monthly' => '0','additional_fee_calculation_method' => '1','mandatory_savings_amount' => '0','is_sms_service_applicable' => '1','minimum_loan_amount_for_sms' => '0','is_actual_daily_basis' => '0','savings_deposit_percentage_new_disburse' => NULL,'savings_deposit_percentage_repeat_disburse' => NULL,'savings_deposit_loan_amount_range' => NULL,'loan_amount_percentage_for_savings_deposit' => NULL,'is_epi' => '0','loan_type' => '','is_fixed_interest_roundup' => '0','audit_fee' => '0','optional_loan_taken' => '0','days_after_disburse' => '0','is_short_term' => '0','is_auto_cal_paramedic_welfare_insurance_amount' => '0','loan_disbursement_stop' => '0','loan_disbursement_stop_from' => '0','loan_disbursement_stop_to' => '0','is_islamic_product' => '0','is_capture_pksf_id' => '0','is_show_auto_process' => '1','insert_time' => '2023-01-04 15:19:21','update_time' => '2023-08-08 12:26:17',],
        ];


        // Cleaning up the table before seeding ...
        $this->db->table('loan_products')->truncate();

        //Using Query Builder Class ...
        try {
        $this->db->table('loan_products')->insertBatch($loan_products);
        } catch (ReflectionException $e) {
            throw new ReflectionException($e->getMessage());
        }
    }
}
